[package]
name = "strava_api"
version = "0.1.0"
authors = ["Francois Best <francois@francoisbest.com>"]
edition = "2018"

[dependencies]
serde = "1.0.83"
serde_json = "1.0.33"
serde_derive = "1.0.83"
reqwest = "0.9.5"
envy = "0.3.3"
